import { Marcellus_SC, DM_Sans, Montserrat } from "next/font/google";
import Marion from 'next/font/local'
import "./globals.css";
import SidebarNav from "@/components/SidebarNav";

const marcellus = Marcellus_SC({
  subsets: ["latin"],
  display: 'swap',
  weight: '400',
  variable: '--font-marcellus'
});

const dm = DM_Sans({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-dm'
});

const marion = Marion({
  src: '../../marion-regular.ttf',
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-marion'
})

const montserrat = Montserrat({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-montserrat'
})

export const metadata = {
  title: "Talents",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#252525] h-full">
      <body className={`h-full ${marcellus.variable} ${dm.variable} ${marion.variable} ${montserrat.variable}`}>
        <SidebarNav/>
        <div className="lg:ml-16 sm+:ml-64">
          {children}
        </div>
      </body>
    </html>
  );
}
