import { Marcellus_SC, DM_Sans } from "next/font/google";
import Marion from 'next/font/local'
import "./globals.css";
import SidebarNav from "@/components/SidebarNav";

export const marcellus = Marcellus_SC({
  subsets: ["latin"],
  display: 'swap',
  weight: '400'
});

export const dm = DM_Sans({
  subsets: ["latin"],
  display: 'swap'
});

export const marion = Marion({
  src: '../../marion-regular.ttf',
  subsets: ["latin"],
  display: 'swap'
})


export const metadata = {
  title: "Talents",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gray-900 h-full">
      <body className={`h-full ${marcellus.variable} ${dm.variable} ${marion.variable}`}>
        <SidebarNav/>
        <div className="ml-16 sm+:ml-64">
          {children}
        </div>
      </body>
    </html>
  );
}
